### ISSUE TITLE
API 

### ISSUE THREAD

**Issue by joeblew99** [jpillora/cloud-gox#4]
Have a few ideas to extend this a little for more usability. I want your opinion beforehand to forumlate what you support first
1. Bitbucket pull support. We use bitbucket for our repos
2. Automatic tagging back to repo of success builds.
3. Notifications of build success failure ?
4. Packaging. This is a hard one because the packaging requirements varies so much.

Also i am wondering where your running this ?

**Comment by jpillora** [comment]
I run two instances on heroku, one public (http://gox.jpillora.com) and one private which has my github creds and performs the releases for all my repos

**Comment by jpillora** [comment]
good ideas
1. two sides of this
   - bitbucket git pulls which as a feature, should probably just be either "support private SSH keys" or "support http basic auth git pulls" to get private repos
   - bitbucket webhooks, on push, bitbucket can send out a request to your server. in this case, cloud-gox would need bitbucket JSON unmarshalling support to extract tags.
2. not sure what you mean by this one?
3. this could be a `SLACK_TOKEN` variable which would be used to post messages
4. packaging does indeed get complex so i've kept it as simple as possible, gzipped binaries. it would be possible to package up .deb files though im not sure how much work goes into this

**Comment by joeblew99** [comment]
1. Sounds great. I don't know too much about this aspect.
2. When the CI server does a successful build, you want to know, and you want to either set a github tag automatically. The other way is to just manually seethe githash,and then tag it on your laptop.
3. Slack is OK. Email is my first preference though as it's the base common denominator that everyone uses.
4. At the moment I have a script that pulls in binaries tat are needed to be part of the build. Then it runs goxc, and outputs a archive. Then it sends it up to s3.

**Comment by joeblew99** [comment]
i realise i made this much more complex than needed.

All i need is bitbucket hooks, and upload to S3 (public and with credentials).

I
