### ISSUE TITLE
Bug: Strange dependency error

### ISSUE THREAD

**Issue by joeblew99** [jpillora/cloud-gox#5]
I started to play around with extending this to have bitbucket handler, and S3 releaser.
I also want to add the ability to embed assets at build time, into a zip. I currently do this with goxc.

Reproduce:
I did a go build and then moved the exe to a different folder, and `./cloud-gox`, and opened localhost:3000, and then it blew up when trying to load the GUI.
From the error message it looks like its the embedded assets.

NOTE: If you dont move the exe out of the src folder, you dont get the error. Probably because the assets are there.

Any chance you could have a look, whilst i add the functionality ?

Env:
I am on OSX and go 1.5

```

x-MacBook-Pro:Downloads apple$ ./cloud-gox 
2016/03/11 10:24:20 cloud-gox started (process user: apple)
2016/03/11 10:24:20 Github missing authentication environment variables
2016/03/11 10:24:20 listening on 3000...
2016/03/11 10:24:32 http: panic serving [::1]:58939: runtime error: invalid memory address or nil pointer dereference
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc8200d8160, 0xc60078, 0xc82002c0d8)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc820067770, 0xc82000ad70, 0x10, 0x0, 0x0, 0x0, 0x0)
    /Users/apple/workspace/go/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0xc601f8, 0xc8200d82c0, 0xc8200f0000, 0xca4708, 0xc820067770, 0xc82000ac14, 0x1, 0xb4e01)
    /usr/local/go/src/net/http/fs.go:394 +0x5b1
net/http.(*fileHandler).ServeHTTP(0xc820063320, 0xc601f8, 0xc8200d82c0, 0xc8200f0000)
    /usr/local/go/src/net/http/fs.go:483 +0x19c
github.com/jpillora/cloud-gox/handler.(*goxHandler).ServeHTTP(0xc82007a6e0, 0xc601f8, 0xc8200d82c0, 0xc8200f0000)
    /Users/apple/workspace/go/src/github.com/jpillora/cloud-gox/handler/handler.go:182 +0x50b
net/http.serverHandler.ServeHTTP(0xc820098420, 0xc601f8, 0xc8200d82c0, 0xc8200f0000)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8200d8160)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6

```

**Comment by jpillora** [comment]
Strange, `go run main.go -p 4000` should work. Maybe update your deps: `go get -u -v .`? Otherwise, explicitly using godeps should work: `godep go run main.go -p 4000`.

**Comment by joeblew99** [comment]
hey. Ok cool. Let me try now...

**Comment by joeblew99** [comment]
`go get -u -v .`did not help. It downloaded it all.

`x-MacBook-Pro:cloud-gox apple$ godep update`also did not help.

Hmmm...

**Comment by jpillora** [comment]
What about `godep go run main.go -p 4000` ?

**Comment by joeblew99** [comment]
godep go run main.go -p 4000 is cheating :)

The whole point i thought was to get it working as a compiled binary ??

**Comment by joeblew99** [comment]
Geez how come your so fast on replying ???

**Comment by joeblew99** [comment]
godep go run main.go -p 4000 does work !

**Comment by joeblew99** [comment]
OH maybe this ??

```
godep diff
godep: dirty working tree (please commit changes): /Users/apple/workspace/go/src/github.com/jpillora/go-realtime
godep: error loading dependencies

```

Nope... I tried deleting this folder and doing a:

```
go get -u -v .
go build
```

, but no dice.

then. i tried a:

```
godep update
go build
```

, but also no dice..

**Comment by jpillora** [comment]
Interesting, so it is definitely a dependency issue.

That says you've made changes to `github.com/jpillora/go-realtime`, could try reseting (`git reset --hard`) that directory?

**Comment by joeblew99** [comment]
tried it. Nope.. same error.

**Comment by joeblew99** [comment]
I can work around it for now easily.  I will work on the other bits for now.
Can we leave this open for now ??

**Comment by ghost** [comment]
maybe its better to change over to : https://github.com/jpillora/velox ??
Its the replacement for go-realtime i noticed.

**Comment by jpillora** [comment]
Yeah just use `godep go run main.go` for now. Indeed velox needs to be swapped in, which will also remove the need for websockets.

**Comment by ghost** [comment]
sweet - thanks !!
